name: GCP Workbench Instance Operations

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment for manual deployment'
        required: true
        type: choice
        options:
        - prod
      gcp_project_id:
        description: 'GCP Project ID'
        required: true
        type: choice
        options:
        - prutwlife-prod-prd-dk6psa-cace
      instance_name:
        description: 'Workbench instance name (ex: aiworkbench)'
        required: true
        type: string
        default: ''
      location:
        description: 'Select the location of the instance'
        required: true
        type: choice
        options:
          - asia-east1-a
          - asia-east1-b
          - asia-east1-c
      action:
        description: 'Select the action to perform'
        required: true
        type: choice
        options:
          - start
          - stop
          - reset
  push:
    branches:
      - main

jobs:
  prepare_vars:
    name: ðŸ§ª Prepare Deployment Variables
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_ENV_TYPE: ${{ steps.vars.outputs.EFFECTIVE_ENV_TYPE_VALUE }} # uat, or prod (logical type)
    steps:
    - name: Set environment
      id: vars
      shell: bash
      run: |
        echo "EFFECTIVE_ENV_TYPE_VALUE=prod" >> $GITHUB_OUTPUT
        
  manage-instance:
    runs-on: ubuntu-latest
    needs: [prepare_vars]
    env:
        DEPLOY_ENV_TYPE: ${{ needs.prepare_vars.outputs.DEPLOY_ENV_TYPE }}
    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v3

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ github.event.inputs.gcp_project_id }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Perform selected action
      run: |
        INSTANCE="${{ github.event.inputs.instance_name }}"
        ACTION="${{ github.event.inputs.action }}"
        PROJECT=${{ github.event.inputs.gcp_project_id }}
        ecgi "======= DEBUG ========
        echo "$env.DEPLOY_ENV_TYPE"
        echo "Performing '$ACTION' on instance '$INSTANCE'..."

        case "$ACTION" in
          start)
            echo gcloud Workbench instances start "$INSTANCE" --project="$PROJECT" --location="$LOCATION"
            ;;
          stop)
            echo gcloud Workbench instances stop "$INSTANCE" --project="$PROJET" --location="$LOCATION"
            ;;
          reset)
            echo gcloud Workbench instances reset "$INSTANCE" --project="$PROJECT" --location="$LOCATION"
            ;;
          *)
            echo "Invalid action: $ACTION"
            exit 1
            ;;
        esac
