name: Manage GCP Workbench Instance

on:
  workflow_dispatch:
    inputs:
      gcp_project_id:
        description: 'GCP Project ID'
        required: true
      instance_name:
        description: 'Select the Workbench instance name'
        required: true
        type: choice
        options:
          - instance-1
          - instance-2
          - instance-3
      action:
        description: 'Select the action to perform'
        required: true
        type: choice
        options:
          - start
          - stop
          - reset

jobs:
  manage-instance:
    runs-on: ubuntu-latest

    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v3

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ github.event.inputs.gcp_project_id }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Perform selected action
      run: |
        INSTANCE="${{ github.event.inputs.instance_name }}"
        ACTION="${{ github.event.inputs.action }}"
        PROJECT=${{ github.event.inputs.gcp_project_id }}

        echo "Performing '$ACTION' on instance '$INSTANCE'..."

        case "$ACTION" in
          start)
            gcloud Workbench instances start "$INSTANCE" --project="$PROJECT" --location="$LOCATION"
            ;;
          stop)
            gcloud Workbench instances stop "$INSTANCE" --project="$PROJET" --location="$LOCATION"
            ;;
          reset)
            gcloud Workbench instances reset "$INSTANCE" --project="$PROJECT" --location="$LOCATION"
            ;;
          *)
            echo "Invalid action: $ACTION"
            exit 1
            ;;
        esac
